version: '3.3'
services:
  orai:
    image: orai/orai:alpine-wasm
    working_dir: /workspace
    tty: true    
    ports:
      - 1317:1317
      - 26656:26656
      - 26657:26657    
    env_file:
      - orai.dev.env
    volumes:        
      - ./:/workspace

  rust:
    image: cosmwasm/rust-optimizer:0.10.7
    entrypoint: tail -f /dev/null
    volumes:
      - .registry_cache:/usr/local/cargo/registry:delegated
      - ./smart-contracts:/code

  simulate:
    image: orai/cosmwasm-simulate:0.11-slim
    tty: true 
    volumes:
      - ./smart-contracts:/code

  proto:
    image: cosmwasm/prototools-docker
    tty: true
    volumes:
      - ./:/work
