version: '3.3'
services:
  orai:
    image: orai/orai:alpine-wasm
    working_dir: /workspace
    tty: true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 1317:1317
      - 40000:40000
      - 26656:26656
      - 26657:26657
    security_opt:
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    env_file:
      - orai.dev.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workspace

  rust:
    image: cosmwasm/rust-optimizer:0.10.7
    entrypoint: tail -f /dev/null
    volumes:
      - ./registry_cache:/usr/local/cargo/registry
      - ./smart-contracts:/code

  proto:
    image: cosmwasm/prototools-docker
    tty: true
    volumes:
      - ./:/work
