version: '3.3'
services:
  node1:
    image: orai/orai:alpine
    working_dir: /workspace/swarm/node1
    networks:
      - net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    tty: true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 1317:1317
      - 40000:40000
      - 26656:26656
      - 26657:26657
    security_opt:
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    env_file:
      - /opt/share/orai/orai.dev.env    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/share/orai:/workspace
      - /opt/share/orai/fn_dev.sh:/usr/local/bin/fn
    #command:
    # - bash -c "fn init && fn createValidator && fn start"

networks:
  net:
    driver: overlay    